name: Format with PHP CS Fixer

on: [pull_request, workflow_dispatch]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: zip
          coverage: none

      - name: Install Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --prefer-dist

      - run: composer run format

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
