name: Tests

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3' ]
        laravel: [ '^11.0' ]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: zip, gd, sqlite, json, gmp, bcmath
          coverage: none

      - name: Ensure we use specific version of Laravel, and install other dependencies
        env:
          LARAVEL_VERSION: ${{ matrix.laravel }}
        run: composer require laravel/framework $LARAVEL_VERSION --no-interaction --no-scripts --prefer-dist

      - name: Execute tests
        run: composer run test
