name: Tests

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: [self-hosted, ubuntu]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: zip, gd, sqlite, json, gmp, bcmath
          coverage: none
        env:
          runner: self-hosted

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit
